### 데이터 합치기

In [1]:
import pandas as pd

In [2]:
_40 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/40까지.csv', encoding = 'euc-kr')
_79 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/79까지.csv', encoding = 'utf-8')
_80 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/80까지.csv', encoding = 'utf-8')
_118 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/118까지.csv', encoding = 'utf-8')
_157 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/157까지.csv', encoding = 'utf-8')
_196 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/196까지.csv', encoding = 'utf-8')
_239 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/239까지.csv', encoding = 'utf-8')
_240 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/240까지.csv', encoding = 'utf-8')
_241 = pd.read_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/241까지.csv', encoding = 'utf-8')

In [3]:
data = pd.concat([_40, _79, _80, _118, _157, _196, _239, _240, _241])
data = data.reset_index()
data = data.drop(['index', 'Unnamed: 0'], axis = 1)
data

,title,run_time,date,view
0,NaN,3:49,2022. 2. 16.,조회수 658회
1,공기업 자소서 = 사기업 자소서 (싱크로율 99%),18:37,2022. 2. 14.,조회수 586회
2,면접스터디 안하면 개이득,10:54,2022. 2. 7.,"조회수 2,259회"
3,2022 상반기 채용전략 3가지만 기억하자.,18:18,최초 공개: 2022. 1. 24.,"조회수 1,244회"
4,최종면접 탈락이유 파헤치기. (feat. 식품회사 해외영업 면접답변 피드백),12:54,2022. 1. 17.,조회수 568회
...,...,...,...,...
236,[취업전략] #4. 2019년 하반기 공채에 사활을 걸어야 하는 이유,7:11,2019. 8. 20.,조회수 765회
237,NaN,7:47,2019. 8. 19.,"조회수 9,138회"
238,[취업공통] #2. FACT와 Detail 없는 자소서는 탈락의 지름길,3:55,2019. 8. 12.,"조회수 1,218회"
239,[취업공통] #1. 차별화는 '소재'가 아닌 '생각'의 차이에서 비롯된다.,4:46,2019. 8. 5.,"조회수 2,622회"
240,"[취업특강] 인재상, 직무역량 따위 필요없다. ""취업의 핵심 3요소"" by Ohms",15:05,최초 공개: 2019. 6. 6.,"조회수 4,234회"

### 결측치 검사

In [4]:
data.isnull().sum()

title       13
run_time     1
date         0
view         0
dtype: int64

### run_time 결측치 처리

In [6]:
data[data['run_time'].isnull()]

                                 title run_time          date        view
40  옴스가 아몰레 올린 AMORE PACIFIC 자소서 완벽 분석      NaN  2021. 5. 12.  조회수 3,896회

In [8]:
data[38:45]

,title,run_time,date,view
38,6/14 월요일 저녁9시 라이브상담,1:25:10,실시간 스트리밍 시작일: 2021. 6. 14.,조회수 710회
39,"2021 하반기 채용트렌드&취업전략, 옴스가 옴스했다.",17:52,2021. 5. 25.,"조회수 1,793회"
40,옴스가 아몰레 올린 AMORE PACIFIC 자소서 완벽 분석,NaN,2021. 5. 12.,"조회수 3,896회"
41,카카오 Service/Biz Developer 사전과제/자소서 작성법 (※말 빠름 ...,13:24,2021. 4. 25.,"조회수 5,420회"
42,NaN,12:19,2021. 4. 5.,"조회수 2,891회"
43,BGF리테일 자소서 작성법 심화 Version? 이건 못참지!!!!,13:35,2021. 4. 1.,"조회수 2,070회"
44,LG에너지솔루션?! 배러리 8분컷?! 이건 못 참지!!!,8:09,2021. 4. 1.,"조회수 6,562회"

In [9]:
data['run_time'][40] = '18:43'

### title 결측치 처리

In [5]:
data[data['title'].isnull()]

    title run_time           date        view
0     NaN     3:49   2022. 2. 16.    조회수 658회
42    NaN    12:19    2021. 4. 5.  조회수 2,891회
75    NaN     9:26  2020. 11. 16.  조회수 2,034회
99    NaN     8:16   2020. 9. 23.  조회수 2,652회
146   NaN    18:41   2020. 5. 31.  조회수 5,037회
168   NaN    12:15   2020. 4. 23.  조회수 4,167회
194   NaN    14:33   2020. 2. 10.  조회수 8,351회
203   NaN    28:09  2019. 12. 26.    조회수 819회
204   NaN    21:32  2019. 12. 15.  조회수 1,605회
209   NaN    27:57   2019. 11. 7.  조회수 5,743회
213   NaN    18:27  2019. 10. 23.  조회수 6,407회
233   NaN     8:48    2019. 9. 2.  조회수 1,945회
237   NaN     7:47   2019. 8. 19.  조회수 9,138회

In [33]:
data[230:239]

,title,run_time,date,view
230,"KT그룹 자소서 완벽해부!!-2탄 ('직무역량, 어려웠던 도전, 공동의 목표' 항목...",15:19,2019. 9. 6.,"조회수 2,408회"
231,KT그룹 지원자들을 위한 지원동기 작성 One Point 레슨!! (KT부터 스카이...,17:04,2019. 9. 4.,"조회수 4,476회"
232,"삼성그룹 신입공채 자소서 해부-1탄!!! (서류전형 카더라부터 취미, 특기, 존경인...",8:16,2019. 9. 3.,"조회수 1,831회"
233,NaN,8:48,2019. 9. 2.,"조회수 1,945회"
234,신용보증기금 자소서 완전 박살내기!! (19하) - 면접대비하시는 분들도 필히 시청...,18:55,2019. 9. 1.,"조회수 2,193회"
235,직무전문성과 관련경험 없이도 취업할 수 있다? 있다!! (좋은 스펙으로도 탈락이 반...,7:45,2019. 8. 26.,"조회수 6,050회"
236,[취업전략] #4. 2019년 하반기 공채에 사활을 걸어야 하는 이유,7:11,2019. 8. 20.,조회수 765회
237,NaN,7:47,2019. 8. 19.,"조회수 9,138회"
238,[취업공통] #2. FACT와 Detail 없는 자소서는 탈락의 지름길,3:55,2019. 8. 12.,"조회수 1,218회"

In [34]:
data['title'][0] = '나이/공백기 질문만 나오면 미치겠습니다.'
data['title'][42] = 'AI면접 실전피드백 "잘못된 답변사례 분석해보기'
data['title'][75] = '마지막 할말로 면접뒤집기? Impossible. 깔끔한 마무리가 핵심.'
data['title'][99] = 'samyang그룹 자소서? 요렇게 공략하라!!!'
data['title'][146] = 'CJ대한통운 신입공채!! *사업+자소서 분석*이 도착했습니다. 구독자님들만 대박나시길 기원합니다.'
data['title'][168] = '해운이 국가 전략사업?? 10분만에 간단하게 끝내는 팬오션 지원전략!!!'
data['title'][194] = '해외영업 5년차 현직자가 썰 푼다. B2B Global Sales란 무엇인가? (해외영업 지원예정자 필독쓰~~~~)'
data['title'][203] = '또 취업재수하고 싶어!? 취업N수생 탈출하자!!! **2020 취뽀를 위한 겨울방학 준비전략**'
data['title'][204] = '토스 레벨6으로 대기업 해외영업/기획 다 씹어 먹는다?? 취업은 스펙이 아니라 마인드가 밥 먹여준다!! 스펙을 뛰어넘는 취업준비 Mindset 대공개 ^^'
data['title'][209] = "※인성/역량/임원면접 한 번에 대비가능한 '면접질문 5대 분류' 확인하기!! (feat. 100문 100답 준비가 오히려 탈락률을 높이는 이유)"
data['title'][213] = '[팩폭주의] 취업나이 카더라 완전종결!! 남자 30살, 여자 27살 이상도 대기업 가능하다!!'
data['title'][233] = '사업보고서 분석법 확실하게 알려줌 1탄 (feat.현대카드)'
data['title'][237] = '회사 관련 경험? 연결고리? 없어도 지원동기 100% 쓸 수 있는 방법.'

In [35]:
data.isnull().sum()

title       0
run_time    0
date        0
view        0
dtype: int64

In [36]:
data.to_csv('C:/Users/hyesu/Desktop/면접왕 이형 데이터 분석/옴스잡스/data.csv', encoding = 'utf-8')